name: .NET WorkFlow

on:
  push:
    branches: [ "master" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'backend/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore backend 
      - name: Build
        run: dotnet build backend --no-restore
      - name: Test
        run: dotnet test backend --no-build --verbosity normal --collect:"XPlat Code Coverage"
